spring:
  h2:
    console:
      enabled: false
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

app:
  security:
    jwt-secret: ${JWT_SECRET:}
